build unfatal qemu

diff --git a/mktoolchain/build-helpers b/mktoolchain/build-helpers
--- a/mktoolchain/build-helpers
+++ b/mktoolchain/build-helpers
@@ -13,6 +13,20 @@ require() {
 	fi
 }
 
+unfatalrequire() {
+	if [ "${1: -3}" = ".so" ]; then
+		ldconfig -p | grep $1 > /dev/null
+	else
+		which $1 > /dev/null
+	fi
+
+	if [ $? = 0 ]; then
+		printf "[\e[95;1mDEPS\e[0m] Found $1\n"
+	else
+		printf "[\e[91;1mFAIL\e[0m] \e[31mDependency not found: $1 (unfatal)\e[0m\n"
+	fi
+}
+
 run() {
 	local text="$1"
 	shift 1
